### PR TITLE
[SDPA-4397] field_landing_page_component's handler_settings issue

### PR DESCRIPTION
**Pull request by vincent-gao**
### Jira
https://digital-engagement.atlassian.net/browse/SDPA-4397

### Issue
we found an issue with `field_landing_page_component`. in its `handler_settings`, `target_bundles_drag_drop` with `TRUE` doesn't match `target_bundles` vice versa. we would like to fix the issue.

### Change
1. adds an update hook to fix the issue described above.

### CODE REVIEW

**Comment by MdNadimHossain** [comment]
@vincent-gao I think this file needs to be updated as well - [field.field.node.landing_page.field_landing_page_component.yml](https://github.com/dpc-sdp/tide_landing_page/blob/develop/config/install/field.field.node.landing_page.field_landing_page_component.yml)
Also, is it possible to use _tide_import_single_config() in this scenario? @anthony-malkoun @GROwen thoughts?

**Comment by vincent-gao** [comment]
> @vincent-gao I think this file needs to be updated as well - [field.field.node.landing_page.field_landing_page_component.yml](https://github.com/dpc-sdp/tide_landing_page/blob/develop/config/install/field.field.node.landing_page.field_landing_page_component.yml)
> Also, is it possible to use _tide_import_single_config() in this scenario? @anthony-malkoun @GROwen thoughts?

just like its comment `Helper to import a single config item (in a quick and dirty way).`. we should avoid use this function. moreover it will change uuid, and not sure if it is suitable for update configurations.

**Comment by GROwen** [comment]
I agree that the use `_tide_import_single_config()` should be avoided and discouraged. Using the Drupal API will ensure there's no custom magic that will cause unintended issues. What @vincent-gao said about it updating the UUID is one of those issues.

I think this is acting on [field.field.node.landing_page.field_landing_page_component](https://github.com/dpc-sdp/tide_landing_page/blob/develop/config/install/field.field.node.landing_page.field_landing_page_component.yml) when this load happens
https://github.com/dpc-sdp/tide_landing_page/pull/94/files#diff-1cb50536ef66dd94cde046ac1401db78R837

Is that right @vincent-gao ?

**Comment by GROwen** [comment]
Was landing page the only module affected by this?

**Comment by vincent-gao** [comment]
> Was landing page the only module affected by this?

@GROwen , I will check all node types that uses `field_landing_page_component` field, I think in a site level, it will check and affect all tide modules. see this line https://github.com/dpc-sdp/tide_landing_page/pull/94/files#diff-1cb50536ef66dd94cde046ac1401db78R833

**Comment by vincent-gao** [comment]
> I agree that the use `_tide_import_single_config()` should be avoided and discouraged. Using the Drupal API will ensure there's no custom magic that will cause unintended issues. What @vincent-gao said about it updating the UUID is one of those issues.
> 
> I think this is acting on [field.field.node.landing_page.field_landing_page_component](https://github.com/dpc-sdp/tide_landing_page/blob/develop/config/install/field.field.node.landing_page.field_landing_page_component.yml) when this load happens
> https://github.com/dpc-sdp/tide_landing_page/pull/94/files#diff-1cb50536ef66dd94cde046ac1401db78R837
> 
> Is that right @vincent-gao ?

Hi @GROwen , yes. that is right. and for all node types.

**Pull request merged**
