### PR TITLE
[SD-231] Moved states js pattern support to global place for all nodes.

### PR DESCRIPTION
**Pull request by MdNadimHossain**
### JIRA 
https://digital-vic.atlassian.net/browse/SD-231

### Issue
Drupal states pattern was not working for promotion and navigation card component for other content types.

### Changes
Removed the JS that has been used only for landing page and moved it to tide_core to get loaded for all content types node.

### Related PR 
https://github.com/dpc-sdp/tide_core/pull/511

### Notes 
Initially it was targeting only landing page as the component was only added for landing pages. Now the component is being used for publication page and it might get used for other content types in the future. So loading it for all node edit forms from tide_core.

### CODE REVIEW

**Review by anthony-malkoun — COMMENTED** [review]
@MdNadimHossain I might be missing the point but should this be in tide core rather than tide landing page? Our is it being added to other content types separately?

**Comment by anthony-malkoun** [comment]
Also, should we be cleaning up the circle jobs of we're no longer using them? Would be nice to have green checks across the board.

**Comment by MdNadimHossain** [comment]
> @MdNadimHossain I might be missing the point but should this be in tide core rather than tide landing page? Our is it being added to other content types separately?

This js was added as a part of promotion and navigation card states pattern use and as the components belongs to landing page, the js was added [here](https://github.com/dpc-sdp/tide_landing_page/blob/2d44d8767110c6f6aa25f587928ceda6bc9de85c/tide_landing_page.module#L117) with the components, so it loads only for landing pages node. Looks like I forgot to remove the other one and that is what created the confusion. 
But I think you are right, if it is going to use globally, it should be added in tide_core.

Pattern example in state - 
` if (isset($element['subform']['field_paragraph_summary'])) {
        $element['subform']['field_paragraph_summary']['widget'][0]['value']['#states'] = [
          'visible' => [
            $selector => [
              ['value' => ['pattern' => '^http']],
              ['value' => ''],
            ],
          ],
        ];`

Let me add it in tide_core and also modify this PR.

**Review by anthony-malkoun — APPROVED** [review]
Thanks for cleaning up @MdNadimHossain!

**Pull request merged**
